### ISSUE TITLE
Request for checkpoints of smaller models

### ISSUE THREAD

**Issue by itayle** [yizhongw/Tk-Instruct#1]
Hi,
Really loved your work!
Thanks for sharing your 3B and 11B checkpoints.
Would it be possible to upload the checkpoints for small models as well? (small, base and large sizes)

**Comment by yizhongw** [comment]
Hi @itayle I have uploaded the smaller models. Now you can find all the released models [here](https://huggingface.co/models?search=allenai/tk-instruct). 

I also want to note that I found a remarkable gap between the smaller models and the 11B or 3B models in generalizing to new tasks. Let me know if you have any interesting findings in playing with them :)

**Comment by itayle** [comment]
Thanks a lot!
Sure, I'll let you know :)
