### ISSUE TITLE
raise RuntimeError("WandbCallback requires wandb to be installed. Run `pip install wandb`.")

### ISSUE THREAD

**Issue by LukeLIN-web** [yizhongw/Tk-Instruct#5]
```
Traceback (most recent call last):
  File "src/run_s2s.py", line 590, in <module>
    main()
  File "src/run_s2s.py", line 484, in main
    callbacks=[DenserEvalCallback] if training_args.denser_evaluation else None
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 407, in __init__
    callbacks, self.model, self.tokenizer, self.optimizer, self.lr_scheduler
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 290, in __init__
    self.add_callback(cb)
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 307, in add_callback
    cb = callback() if isinstance(callback, type) else callback
  File "/opt/conda/lib/python3.7/site-packages/transformers/integrations.py", line 542, in __init__
raise RuntimeError("WandbCallback requires wandb to be installed. Run `pip install wandb`.")
```
I can import wandb, but cannot callback.

python : 3.7.11
pip list:   has installed wandb                   0.12.10
conda list :wandb                     0.12.10                  pypi_0    pypi
which wandb :    /opt/conda/bin/wandb
which pip : /opt/conda/bin/pip

**Comment by LukeLIN-web** [comment]
Really strange,  wandb login
wandb: Currently logged in as: lukelin (use `wandb login --relogin` to force relogin)


    import wandb
    wandb.init(project="my-awesome-project")
But it still shows RuntimeError: WandbCallback requires wandb to be installed. Run `pip install wandb`.

**Comment by yizhongw** [comment]
I am not sure why hf library cannot detect your installed wandb. Probably this [document](https://docs.wandb.ai/guides/integrations/huggingface#2-name-the-project) is helpful.

**Comment by LukeLIN-web** [comment]
> I am not sure why hf library cannot detect your installed wandb. Probably this [document](https://docs.wandb.ai/guides/integrations/huggingface#2-name-the-project) is helpful.

Well, I clone the newest repo,  it successfully detect my wandb.

**Comment by scris** [comment]
I think the solution is, you explicitly declare that, export WANDB_DISABLED=False.
