### ISSUE TITLE
No dev.txt file in the current natural instruction repo

### ISSUE THREAD

**Issue by ruiqi-zhong** [yizhongw/Tk-Instruct#7]
https://github.com/yizhongw/Tk-Instruct/blob/620a0091759e46210a75575d0d0e761c430569d2/src/ni_dataset.py#L126 the script is assuming that there is a `dev_tasks.txt `file. However, the [current NI Repo](https://github.com/allenai/natural-instructions/tree/master/splits/default) does not seem to have the `dev_tasks.txt` file. Can I simply remove the line loading validation set to run the evaluation script? 

Thanks!

**Comment by yizhongw** [comment]
I think it can work. Or you can create an empty `dev_tasks.txt`, then the evaluation script should work.
